# Generated by Django 4.1.3 on 2023-08-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_search_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_history',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
